#import "../template/fom.typ": *
= Einleitung
== Problemstellung
In den frühen 1970er-Jahren gab es in Chile, unter der Regierung von Salvador Allende, ein Projekt, bei dem versucht wurde, die Wirtschaft eines Landes anhand von computergestützten Systemen durch Management-Kybernetik zu steuern. Das Projekt trug den Namen Cybersyn, #vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 1)eine Abkürzung von #emph()[cybernetic synergy].#vgl(<brain-of-the-firm>, seite: 252)
Trotz seiner für die 1970er-Jahre innovativen Ideen wird das Projekt Cybersyn nur wenig innerhalb des deutschen Raums – sowie auch international – erforscht. Diese Forschungslücke zu dem Projekt Cybersyn ist 2018 auch Katharina Loeber in ihrer Arbeit #emph()["Big Data, Algorithmic Regulation, and the History of the Cybersyn Project in Chile, 1971–1973"] aufgefallen und nennt das Buch #emph()["Cybernetic Revolutionaries"] von Eden Medina als die moderne Arbeit zu dem Cybersyn-Projekt die bei jeder arbeit zu Cybersyn zitirt wird.#vgl(<loeberBigDataAlgorithmic2018a>, seite: 2) Die Arbeit von Eden Medina wird grade in den grundlagen kaptieln sowie den Historischen hintergrunden stark zitirt, ebenso stammen viele primär quellen aus den quellen verzeichnis medinas. Viele Ideen, die in dem Projekt Cybersyn zum Tragen gekommen sind, werden heute in modernen Monitoring- und Decision-Support-Systemen – wie sie bei großen Unternehmen wie Amazon aufzufinden sind – wieder aufgegriffen. Da das Thema nur wenig erforscht ist, gibt es derzeit keinen prägnanten Überblick über die Erkenntnisse, die aus dem Cybersyn-Projekt gezogen werden können und in modernen Monitoring- und Decision-Support-Systemen Anwendung finden.
== Zielstellung
Die Seminararbeit hat das Ziel, einen prägnanten Überblick über die Erkenntnisse zu geben, die aus dem Cybersyn-Projekt gezogen werden können. Um einen Überblick zu geben, werden folgende Punkte betrachtet:
+ Erklärung theoretischer Grundlagen des Projekts Cybersyn.
+ Wie war das Cybersyn-Projekt aufgebaut.
+ Warum ist das Cybersyn-Projekt gescheitert.
+ Welche Ideen aus dem Cybersyn-Projekt sind auf moderne Monitoring- und Decision-Support-Systeme anwendbar.
Die Leser*innen sollen nach dem Lesen verstehen, was das Projekt Cybersyn erreichen wollte und warum das Projekt nicht vollendet wurde. Zusätzlich sollen die Leser*innen einen Überblick über die fortschrittlichen Ideen des Cybersyn-Projekts haben und wie sie heute angewendet werden.
