#import "../template/fom.typ": *
= Einleitung
== Problemstellung
Ab 1971 versuchte die Regierung Salvador Allendes in Chile, die Wirtschaft des Landes mit computergestützten Systemen durch Management-Kybernetik zu steuern. Das Projekt hieß Cybersyn,#vgl-kap(<medinaCyberneticRevolutinaries2014>, kap: "1 Cybernetics and Socialism") eine Abkürzung von #emph()[cybernetic synergy].#vgl(<brain-of-the-firm>, seite: 252) Cybersyn ist nur wenig erforscht; dies ist auch Katharina Loeber aufgefallen.#footnote[Der Aufsatz erschien in der Zeitschrift #emph[Social Sciences] (MDPI), die ihre Beiträge fortlaufend nummeriert, statt Heftseiten zu vergeben; „Art.-Nr. 65“ im Literaturverzeichnis ist diese Artikelnummer und keine Seitenzahl. Seitenangaben zu diesem Aufsatz beziehen sich in dieser Seminararbeit auf die PDF-Fassung (15 Seiten).]  Sie bezeichnet Eden Medinas Buch #emph()[„Cybernetic Revolutionaries“]#footnote[Cybernetic Revolutionaries wird in dieser Seminararbeit ebenfalls oft zitiert; auch Primärquellen aus Cybernetic Revolutionaries werden genutzt. Während des Schreibens der Seminararbeit lag mir die 2014er Version bei Apple Books vor, deshalb zitiere ich auch nur aus Kapiteln und nicht mit Seitenzahl, da Apple Books nicht mit den Druckseiten arbeitet.] als das maßgebliche Werk zu Cybersyn, das in nahezu jeder Arbeit zum Thema zitiert wird.#vgl(<loeberBigDataAlgorithmic2018a>, seite: 2) Viele Ideen aus Cybersyn werden heute in modernen Monitoring- und Decision-Support-Systemen wieder aufgegriffen. Da das Thema kaum erforscht ist, fehlt bislang ein prägnanter Überblick über die Erkenntnisse aus Cybersyn und deren Anwendung in solchen Systemen.
== Zielstellung
Die Seminararbeit gibt einen prägnanten Überblick über die Erkenntnisse aus Cybersyn. Dazu werden folgende Punkte betrachtet:
+ Theoretische Grundlagen.
+ Verlauf und Aufbau Cybersyns.
+ Aufbau moderner Monitoring- und Decision-Support-Systeme.
+ Übertragbarkeit der Ideen aus Cybersyn auf moderne Monitoring- und Decision-Support-Systeme.
