#import "../template/fom.typ": *
= Grundlagen der Management-Kybernetik
== Kybernetik
Kybernetik ist ein nicht klar definierbarer Begriff, da viele Kybernetiker*innen dem Begriff eine unterschiedliche Bedeutung zusprechen. In der Literatur zu Cybersyn wird oft Gebrauch von der 1948 entstandenen Definition nach dem MIT-Mathematiker Norbert Wiener aus dem Paper #emph()["Cybernetics: Or Control in the Animal and the Machine"] gemacht #vgl(<cCyberneticsStateArt2017>, seite: 2). Das hat den Hintergrund, dass Eden Medina in ihrem 2011 erschienenen Werk „Cybernetic Revolutionaries“ eben diese Definition mit dem Projekt Cybersyn verquickt hat. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 23) Da die Definition Wieners in der Literatur zu Cybersyn oft verwendet wird – nicht nur weil Eden Medina diese in ihrem Werk nutzte – sondern auch, da Wiener oft als Vater der Kybernetik bezeichnet wird und im Kontakt zu Stafford Beer stand und diesen als Vater der Management-Kybernetik bezeichnet. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 23)
=== Kybernetik nach Norbert Weiner
Wieners Definition beschreibt Kybernetik als ein Forschungsfeld, welches die Forschungsfelder der Kommunikationstheorie, Berechenbarkeit, Automatentheorie und Neurophysiologie vereint. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 23)  #zitat(<wienerHumanUseHuman1988>) Kybernetik wird von dem griechischen Wort #emph()[kubernêtês] abgeleitet, es kann auf mehren weisen übersetzt werden. Ein benkannte übersetzung ist Steuermann, da die Person welche eine #emph()[trireme] – eine bauart von Kreigsschiffen im antiken greicheland – befehleigt haben in dem Antiken grichenland #emph()[kubernêtês] gennant wurden. Andere übersetzung je nach kontext können aber auch Regieren, Regulation und Management sein. Der Steuermann und die weiteren bedeutung des wortes #emph()[kubernêtês] sind ein gutes Sinnbild für das Ziel von Kybernetik: das Verstehen der Gemeinsamkeiten von Maschinen und Organismen in den Bereichen der Kommunikation, Feedback und Steuerung. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 24)  #vgl(<cCyberneticsStateArt2017>, seite: 3)
== Management-Kybernetik
Stafford Beer, die Schlüsselfigur und der Architekt hinter dem Cybersyn-Projekt #vgl(<medinaCyberneticRevolutinaries2014>, seite: 20), ist bekannt für seine Arbeit in einer besonderen Ausprägung der Kybernetik, nämlich der Management-Kybernetik. Beer wurde auch von als Vater der Management-Kybernetik bezeichnet.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 23) Die Management-Kybernetik ist ein Intergaler Bestand teil des Cybersyn projekt da diese der Grundbaustein für das Cybersyn Projekt ist. Viele der ideen die in Kapitel 3 Später besprochen werden sind ledglich versuche Management-Kybernetik in der Realen Welt umzusetzen.
=== Definition von Management-Kybernetik
Bei der Management-Kybernetik wird versucht, durch kybernetische Methoden ein Unternehmen oder sogar – wie im Projekt Cybersyn – eine Wirtschaft eines ganzen Landes zu steuern und zu optimieren, eben durch aus der Kybernetik stammende Feedback-Loops und Kommunikation. Beer versteht eine Wirtschaft als ein System, vergleichbar mit einem Organismus. Um Beers ideen besser zu verstehen muss man auch ein besonderers Modell von Beer Verstehen nämlich das #emph()[Viabel System Modell].
=== Viabel System Modell
