#import "../template/fom.typ": *
= Grundlagen der Management-Kybernetik
Dieses Kapitel behandelt die Grundlagen der Management-Kybernetik. Um diese zu verstehen – insbesondere im Bezug zu dem Cybersyn-Projekt – muss auch der Begriff der Kybernetik erklärt werden. Die Begriffe sind miteinander verknüpft, da die Management-Kybernetik eine besondere Ausprägung der Kybernetik ist. Aber auch in dem Feld der Management-Kybernetik gibt es Modelle und Begriffe, die eine gesonderte Definition verdient haben.
== Kybernetik
Kybernetik ist ein nicht klar definierbarer Begriff, da viele Kybernetiker*innen dem Begriff eine unterschiedliche Bedeutung zusprechen. In der Literatur zu Cybersyn wird oft Gebrauch von der 1948 entstandenen Definition nach dem MIT-Mathematiker Norbert Wiener aus dem Paper #emph()["Cybernetics: Or Control and Communication in the Animal and the Machine"] gemacht #vgl(<cCyberneticsStateArt2017>, seite: 2). Das hat den Hintergrund, dass Eden Medina in ihrem 2011 erschienenen Werk #emph()[Cybernetic Revolutionaries: Technology and Politics in Allende’s Chile] eben diese Definition mit dem Projekt Cybersyn verquickt hat. #zit(<medinaCyberneticRevolutinaries2014>, seite: 23) Nicht nur, weil Eden Medina diese in ihrem Werk nutzte, sondern auch, da Wiener oft als Vater der Kybernetik bezeichnet wird und im Kontakt zu Stafford Beer stand und diesen als Vater der Management-Kybernetik bezeichnet.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 23) Ist Wieners Definition der Standard bei Literatur zu dem Cybersyn-Projekt.
=== Kybernetik nach Norbert Wiener
Wieners Definition beschreibt Kybernetik als ein Forschungsfeld, welches die Forschungsfelder der Kommunikationstheorie, Berechenbarkeit, Automatentheorie und Neurophysiologie vereint. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 23) Kybernetik wird von dem griechischen Wort #emph()[kubernêtês] abgeleitet, es kann auf mehrere Weisen übersetzt werden. Eine bekannte Übersetzung ist Steuermann, da die Person, welche eine #emph()[trireme] – eine Bauart von Kriegsschiffen im antiken Griechenland – befehligt haben, in dem antiken Griechenland #emph()[kubernêtês] genannt wurden. Andere Übersetzungen je nach Kontext können aber auch Regieren, Regulation und Management sein. Der Steuermann und die weiteren Bedeutungen des Wortes #emph()[kubernêtês] sind ein gutes Sinnbild für das Ziel von Kybernetik: das Verstehen der Gemeinsamkeiten von Maschinen und Organismen in den Bereichen der Kommunikation, Feedback und Steuerung. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 24)  #vgl(<cCyberneticsStateArt2017>, seite: 3)
== Management-Kybernetik
Stafford Beer, die Schlüsselfigur und der Architekt hinter dem Cybersyn-Projekt #vgl(<medinaCyberneticRevolutinaries2014>, seite: 20), ist bekannt für seine Arbeit in einer besonderen Ausprägung der Kybernetik, nämlich der Management-Kybernetik. Beer wurde auch als Vater der Management-Kybernetik bezeichnet.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 23) Die Management-Kybernetik ist ein integraler Bestandteil des Cybersyn-Projekts, da diese der Grundbaustein für das Cybersyn-Projekt ist. Viele der Ideen, die in Kapitel 3 später besprochen werden, sind lediglich Versuche, Management-Kybernetik in der realen Welt umzusetzen.
=== Definition von Management-Kybernetik
Bei der Management-Kybernetik wird versucht, durch kybernetische Methoden ein Unternehmen oder sogar – wie im Projekt Cybersyn – eine Wirtschaft eines ganzen Landes zu steuern und zu optimieren, eben durch aus der Kybernetik stammende Feedback-Loops und Kommunikation. Beer versteht eine Wirtschaft als ein System, vergleichbar mit einem Organismus. Beer Fokus bei der Management ist Handeln, anstatt Modellierung von Daten wie bei der Kybernetik nach Wiener #vgl(<medinaCyberneticRevolutinaries2014>, seite: 34)
=== Viable System Model
Um Beers Ideen besser zu verstehen, muss man auch ein besonderes Modell von Beer verstehen, nämlich das #emph()[Viable System Model].
