#import "../template/fom.typ": *
= Das Cybersyn-Projekt
In diesem Kapitel wird das Projekt Cybersyn tiefer behandelt. Erst wird der historische Kontext dargestellt, da dieser wichtig ist, gerade um das abrupte Ende des Projekts zu verstehen. Daraufhin wird der technische Aufbau des Projektes Cybersyn erläutert sowie, wie Cybersyn genutzt wurde und was noch geplant war. Zum Abschluss des Kapitels wird aufgezeigt, wie das Projekt gescheitert ist.
== Historischer Hintergrund und Rahmenbedingungen
Das Projekt Cybersyn fand von 1971 bis 1973 statt #vgl(<medinaCyberneticRevolutinaries2014>, seite: 15).
\ Bei der Präsidentschaftswahl am 4. September 1970 in Chile gewann die #abk("UP") – ein ehemaliger Zusammenschluss von linken, sozialistischen und kommunistischen Parteien – mit dem Kandidaten #emph()[Salvador Allende]#vgl(<bildung1970SalvadorAllende2015>, seite: 1) und 1,3 % Vorsprung gegenüber dem ehemaligen Präsidenten Chiles #emph()[Jorge Alessandri] #vgl(<medinaCyberneticRevolutinaries2014>, seite: 51). Allende war ein Sozialist und hatte das Ziel, die Industrie im Besitz von multinationalen Konzernen und der chilenischen Oligarchie zu verstaatlichen #vgl(<bildung1970SalvadorAllende2015>, seite: 2) und Chile durch Reformen zu einem sozialistischen Staat zu formen, der allerdings alle demokratischen Institutionen aufrechterhält. Durch die Unterschiede zu der Umsetzung des Sozialismus wurde Allendes Ansatz bekannt als „chilenischer Weg zum Sozialismus“. #vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 1)
\ Ein Grund für die Verstaatlichung der Industrie hängt mit den #abk("USA") zusammen. In einer Rede vor den Vereinten Nationen am 4. Dezember 1972 erwähnte Allende, dass in den letzten 42 Jahren Konzerne aus den #abk("USA") mit einem Investment von 30 Millionen in der chilenischen Industrie Einnahmen von 4 Milliarden generieren konnten, während Teile der chilenischen Bevölkerung sich nicht vernünftig ernähren konnten. #vgl(<SalvadorAllendeSpeech>, seite: 2) Die #abk("USA")  wiederum haben von 1962 bis 1969 im Rahmen des #emph()[Alliance for Progress]-Programms über eine Milliarde US-Dollar an Hilfen an Chile gesendet,#vgl(<CovertActionChile>, seite: 151) mit dem Ziel, den Lebensstandard in Chile anzuheben und die chilenische Bevölkerung von dem Kommunismus abzuwenden. #vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 1) Die Verstaatlichung hat der chilenischen Regierung so zwei Probleme eingebracht. Die US-Regierung wollte den sozialistischen Weg der Allende-Regierung verhindern; dafür startete sie eine verdeckte Operation, indem sie Oppositionsparteien und Medien finanzierte. #vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 2)
\ Das andere Problem ist für den Start des Cybersyn-Projekts viel relevanter. Nachdem Allendes Regierung die Industrie verstaatlicht hatte, stand sie vor dem Problem, die Unternehmen samt ihrer Mitarbeiter zu steuern. Um diese Probleme zu lösen, kam #emph()[Fernando Flores], der während Allendes Regierung technischer Generaldirektor der #abk("CORFO") – der chilenischen Staatsentwicklungsbehörde #vgl(<medinaCyberneticRevolutinaries2014>, seite: 10) – war, auf die Idee, den britischen Kybernetiker #emph()[Stafford Beer] zu kontaktieren. Stafford Beer hatte zwölf Jahre zuvor ein Buch über Management-Kybernetik namens #emph()[Cybernetics and Management] geschrieben. Flores hatte das Buch gelesen und hoffte, dass die Steuerung der Wirtschaft Chiles durch Management-Kybernetik erleichtert werden könnte. #vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 2)
#abbildung(
  align(center, image("../abbildungen/CORFO-Hierachie2.png", width: 100%)),
  titel: [Hierarchie der Verstaatlichung durch die CORFO vor Cybersyn],
  quelle: [Eigene Darstellung in Anlehnung an Texte aus Cybernetic Revolutionaries #zitat(<medinaCyberneticRevolutinaries2014>, seite: 54)],
)<abb-hCvCnsy>
Vor dem Kontakt zu Beer hatte die #abk("CORFO") bereits Bemühungen unternommen, die verstaatlichten Firmen zu steuern. Wie in @abb-hCvCnsy zu sehen, wurde die Wirtschaft in vier Zweige – auch #emph()[ramas] genannt #vgl(<brain-of-the-firm>, seite: 250) – unterteilt:
+ Konsumgüter
+ Leichtindustrie
+ Baumaterialien
+ Schwerindustrie
Jeder Zweig hatte jeweils untergeordnete Sektoren. Die Unternehmen innerhalb der Sektoren wurden von sogenannten #emph()[Interventoren] – das Wort ist eine chilenische Wortneuschöpfung – überwacht. Die emph()[Interventoren] wurden on der Regierung eingesetzt um die bisherigen Eigentümer und Manager zu ersetzen. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 54) Die Sektoren wurden jeweils von einem Komitee überwacht.
Das Problem dabei war, dass die Komitees und auch die Interventoren keine klaren Rollen hatten. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 60) Zusätzlich gab es in manchen Sektoren zu wenig qualifizierte Interventoren. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 60) Daraus ergaben sich erst die Managementprobleme, weshalb Flores Beer kontaktierte.
\ Beer erhielt 1971 den Brief von Fernando Flores. #vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 2) Beer war zu der Zeit als Berater in England tätig und konnte daher nicht direkt nach Chile. Für Beer war die Einladung unwiderstehlich, da er so seine Ideen auf nationaler Ebene testen konnte. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 19) Beer ließ seine Beraterverträge auslaufen und kam vier Monate nach der Einladung von Flores nach Chile – am 4. November 1971, zugleich dem ersten Jahrestag von Allendes Regierung –, um seine Arbeit an dem Projekt zu beginnen.
== Architektur und Entstehung
Schon im November 1971 gab es ein klares Ziel für das Projekt Cybersyn: Bis zum 1. März 1972 sollte eine vorläufige Version des Cybersyn-Projektes installiert werden, welche die Fähigkeiten der Management-Kybernetik aufzeigt. #vgl(<brain-of-the-firm>, seite: 252)
\ Beer hatte das #abk("VSM") bereits entwickelt und gab den Mitarbeiter\*innen an dem Projekt die Manuskripte für #emph()[Brain of the Firm]. #vgl(<brain-of-the-firm>, seite: 248)
Flores war von Beers Modell überzeugt. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 62)
#abbildung(
  align(center, image("../abbildungen/VSM-Rekursion-Beer.png", width: 65%)),
  titel: [VSM-Rekursion nach Beer: Anwendung auf den chilenischen Staat],
  quelle: [Eigene Darstellung in Anlehnung an Auszüge aus Beers Bericht #emph()[Cybernetic Notes on the Effective Organisation of the State with Particular Reference to Industrial Control] #zitat(<brain-of-the-firm>, seite: 249)],
)<abb-beer-chile-mappin>
Beer erstellte während seines Besuchs im November 1971 zwei Berichte, der erste Bericht heißt #emph()[Cybernetic Notes on the Effective Organisation of the State with Particular Reference to Industrial Control]. Dieser beschäftigte sich damit, wie der chilenische Staat in dem #abk("VSM") abgebildet werden könnte.
#vgl(<medinaCyberneticRevolutinaries2014>, seite: 77) In diesem wendete Beer das #abk("VSM") auf den chilenischen Staat an, zu sehen in @abb-beer-chile-mappin. Hier zeigt sich explizit, wie Rekursion in dem #abk("VSM") angewendet wird. #vgl(<brain-of-the-firm>, seite: 249) Beer stellte Allende das Modell am 12. November 1971 vor. #vgl(<brain-of-the-firm>, seite: 257) Als Beer Allende das #abk("VSM") aufzeichnete und bei System 5 angekommen war, ging Allende davon aus, dass System 5 die Bevölkerung sei. #vgl(<brain-of-the-firm>, seite: 258) Später prägte dies die Idee, die Bevölkerung durch Feedback einzubinden.
Der zweite Bericht war ein Plan- und Projektantrag für das Vorläuferprojekt von Cybersyn, mit dem Namen Cyberstride.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 78)
=== Cyberstride – Die Statistik-Software
Cyberstride war ein Softwarepaket, entwickelt von der #abk("ECOM") und dem Londoner Büro der US-amerikanischen Unternehmensberatung Arthur Andersen.#vgl(<bildungKybernetischeRevolutionUnd2023>, seite: 4) Cyberstride sollte durch statistische Berechnung und Überwachung von System 1–3 auf nationaler Ebene, Informationen über die Betriebe bereitstellen und leicht zugänglich machen. Gleichzeitig sollte es System 4 und 5 informieren und die Daten durch statistische Berechnungen für die Zukunft hochrechnen um Vorhersagen für die Zukunft zu erstellen. #vgl(<brain-of-the-firm>, seite: 261) Durch Cyberstride wäre es theoretisch möglich auf Ereignisse wie beispielsweise Knappheit von Rohmaterialien, besser zu reagieren da die Komitees – bestehend aus erfahrenen Managern – die Interventoren besser beraten und leichter Probleme identifizieren konnten. Cyberstride sollte kontinuierlich und schnell Informationen liefern. Um dies zu ermöglichen wollte Beer ein Netzwerk aus Computern schaffen als Rückgrat für das Cyberstride. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 78)
=== Cybernet – Das Netzwerk
Doch bei der Umsetzung eines solchen Netzwerkes gab es einige Hürden. Die #abk("ECOM") – das nationale Computerzentrum Chiles – hatte 1971 nur vier Mainframes #vgl(<medinaCyberneticRevolutinaries2014>, seite: 63) von denen Beer nur einen nutzen durfte. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 79) Die Mainframes waren von IBM. IBM hatte sich aus Angst vor Verstaatlichung größtenteils aus Chile zurückgezogen, nachdem Allende gewählt worden war. Durch die zusätzliche US-Blockade war es nicht möglich weiter Computer von IBM zu kaufen. Computer von anderen Herstellern – wie die des französischen Herstellers #abk("CII") – waren inkompatibel mit den IBM-Computern. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 72) Um ein Netzwerk mit nur einem Mainframe aufzubauen, wurden Telexmaschinen genutzt. Telexmaschinen, kurz für #emph()[Teleprinter Exchange], werden auch Fernschreiber genannt. Telexmaschinen waren Schreibmaschinen mit einer klar identifizierbaren Nummer – wie eine Telefonnummer. Diese konnte man eingeben und eine Nachricht an eine andere Telexmaschine senden. Sie waren an die bereits existierenden Telefon- und Satellitennetze angeschlossen. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 79)
#abbildung(
  align(center, image("../abbildungen/Telex-Aufbau.png", width: 75%)),
  titel: [Einsatz des Telexnetzwerks zum Austausch von Informationen],
  quelle: [Eigene Darstellung in Anlehnung an #zitat(<medinaCyberneticRevolutinaries2014>, seite: 79)],
)<abb-telex-aufbau>
In @abb-telex-aufbau ist aufgezeigt wie die Kommunikation über das Telexnetzwerk abgelaufen ist. Die Interventoren innerhalb einer Firma hatten ein Telexgerät mit dem sie ihre Daten an die #abk("ECOM") übertrugen. Dort wurden die Daten in den Mainframe eingespeist. Auf diesem wurden durch das Cyberstride-Programm statistische Berechnungen durchgeführt. Eine Besonderheit in @abb-telex-aufbau ist die Benachrichtigung der #abk("CORFO") bei Ausnahmen. Wenn Ausnahmen auftraten wurde der Interventor des Unternehmens benachrichtigt. Gleichzeitig berieten sich die Interventoren aus einem Bereich gegenseitig wie sie mit der Ausnahme umgehen und eine Lösung finden. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 79) Beers Ziel war eine ehrliche Kommunikation zwischen Interventoren und #abk("CORFO"), durch die statistischen Berichte war es schwer für Interventoren Produktionsdaten zu fälschen. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 80) Später erhielt das Netzwerk den Spitznamen #emph()[Cybernet].#vgl(<brain-of-the-firm>, seite: 252)
=== Checo – Die Wirtschaftssimulation
Während der Entwicklung der Cyberstride-Software kam Beer auf die Idee nicht nur statistische Berechnung für das Tagesgeschäft zu erstellen, sondern auch eine Wirtschaftssimulation für tiefergehende Zukunftsvorhersagen. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 89) So entstand #emph()[Checo] kurz für Chilean Economy Simulator.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 94) Beer sah Checo als eine Implementierung des Systems 4. Wie in @abb-vsm dargestellt hat System 4 zwei Aufgaben: die Kommunikation zwischen System 3 und 5 – als eine Art Mediator #vgl(<brain-of-the-firm>, seite: 266) – und die Betrachtung der Zukunft. #vgl(<brain-of-the-firm>, seite: 264) System 5 war wie in @abb-beer-chile-mappin aufgezeigt die Regierung. Checo war laut Beer ein experimentelles Labor für die Regierung. Das Labor sollte die Regierung bei Entscheidungen unterstützen, da sie Prognosen hatte, welche Auswirkungen ihre Entscheidungen auf die Wirtschaft haben würden. #vgl(<medinaCyberneticRevolutinaries2014>, seite: 89)
\ Beer wollte mit Checo keine einfache Input-Output-Analyse schaffen.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 89) Aus Beers Sicht waren diese strukturarm, stochastische Elemente kaum einführbar und statisch, daher waren sie für das #abk("VSM") ungeeignet. Zusätzlich wurden für Input- und Output-Modelle große Datenmengen benötigt, die zunächst gesammelt werden mussten. Dies war durch die Deadline des Projekts März 1972 nicht umsetzbar. Beer nutzte deshalb die Sprache DYNAMO, erschaffen von J. W. Forrester. Mit dieser hatte Beer auch schon Vorerfahrung gesammelt.#vgl(<brain-of-the-firm>, seite: 266) Im September 1972 war bereits eine kleine Version des Modells fertiggestellt, allerdings waren die Daten oft nicht zuverlässig weshalb es große Schwankungen bei dem Modell gab.#vgl(<brain-of-the-firm>, seite: 267) Eine Idee die Beer für Checo vorgesehen hatte war es jeden Tag eine Simulation bis zu 10 Jahre in die Zukunft laufen zu lassen. Dies wurde nie umgesetzt.#vgl(<brain-of-the-firm>, seite: 268)
=== Der Operationsraum
Der Operationsraum kam erst im März 1972 zu dem Projekt hinzu, als aus dem Vorläuferprojekt Cyberstride das Projekt Cybersyn wurde. Das Ziel von Projekt Cybersyn war es die vorherigen Elemente also die Programme Cyberstride, Cybernet und Checo miteinander zu verbinden und über den Operationsraum zu steuern. Dies sollte bis November 1972 umgesetzt sein.#vgl(<medinaCyberneticRevolutinaries2014>, seite: 96)
\ Der Operationsraum war von #emph()[War Rooms] aus dem 2. Weltkrieg inspiriert. In #emph()[War Rooms] gab es einen Balkon in dem hochrangige Offiziere saßen, aus dem Balkon blickten sie auf einen großen Tisch auf welchem sich eine Karte des Schlachtfelds befand. Die unterschiedlichen Truppen wurden durch Figuren dargestellt. Diese wurden basierend auf Live-Daten bewegt. So konnten die Offiziere nicht nur aus der Ferne Entscheidungen treffen sondern hatten auch einen dauerhaften Überblick über die wichtigsten Daten. #vgl(<brain-of-the-firm>, seite: 193)
#abbildung(
  align(center, image("../abbildungen/Ops-Room.png")),
  titel: [Aufbau des Operationsraum],
  quelle: [Eigene Darstellung in Anlehnung an #zitat(<brain-of-the-firm>, seite: 269) und 3D Render von #zitat(<ProjectCybersyn2026>)],
)<abb-opsroom>
Das Design des Operationsraums kam vom #abk("INTEC") unter der Leitung von #emph()[Gui Bonsiepe].#vgl(<brain-of-the-firm>, seite: 268) In @abb-opsroom ist das Design des Raums aufgezeigt. Zu erkennen ist die hexagonale Form mit einem Durchmesser von 10 Metern. Trotz der 6 Wände wurden 5 benutzt.#vgl(<brain-of-the-firm>, seite: 268)
#tabelle(
  table(
    columns: 3,
    [Gerät], [Aufbau], [Aufgabe],
    [Animiertes #abk("VSM")],
    [Ein Zwei Meter Hoher Schrank in dem rotierende Polarisationsscheiben – eine möglcihkeit für meachnische animation – das #abk("VSM") an eine Wand im Schrank Projezierte so das es von außen sichtbar ist.],
    [Die Polarisationsscheiben konnten beschrift werden, die beschriftung wurden für jedes Meeting angepasst so das man das aktuell mapping des #abk("VSM") sehen konnte.],

    [Alarm Bildschirme],
    [Es gab zwei Bildschirm welche von handbedien werden mussten.],
    [Die Arlam bildschrimen zeigt warnungen für System 3,4 und 5 falls abweichungen eintreten.],

    [Alegdonsiche Warnleuchte],
    [Wurde durch blinken zweier Roter leuchten signalsiret.],
    [Alegdonisch ist ein von Beer Geschaffener begriff er setzt sich aus dem Griechischen: algos (Schmerz) + hedone (Lust/Vergnügen). Es bezeichnet ein Signal, für eine abweichung ohne zusatz infomrationen.#vgl(<brain-of-the-firm>, seite: 401) Die Lampen leuchten bei abweichung  von unterleigeden systemen – also 1 und 2 – der Live daten zu den Berechnungen aus der Checo Simulation.],

    [Data Feed],
    [Der Data Feed bestand aus 3 bildschrimen mit je 5 Rückprojektoree, diese wurden eiengestz um das flackern eines rühen bildschrims zu vermeden. Zusatlich gab es eine Wieter Bildschirm der von nur einem Rückprojektore betreiben wurde um eine Legende der Elemente anzuzeigen],
    [Der Data Feed war eine Anzeige des Daten aus dem Cyberstride program welche über die Kontrollen der Stühle Navigeirt werden könnte.],

    [Checo Simulation],
    [Die Simulation sollte durch eine Hybrid Rechner – welcher nie zustande kam – basiert auf einegaben berechnet werden. Staatdessen wurden Ruckprojektoren wie bei dem Data Feed genutzt.],
    [Durch die Simulation sollte geprüft werden ob eine entschediug einen postiven oder eine nergative auswirkung auf die wirtschaft hat.],
  ),
  titel: [Bestandteile des Operationsraum],
  quelle: [Eigene Darstellung in Anlehnung an #zitat(<brain-of-the-firm>) Seite 268 - 270],
) <tab-opsroom-aufbau>
Die Mitte des Raums war hindernislos.#vgl(<brain-of-the-firm>, seite: 268) Um die Mitte des Raums waren 7 Stühle in einem Kreis angeordnet. Die Stühle wurde extra so angeordnet dass Arbeiter\*innen aus jedem stuhl – welche drehfüße besaßen – alles im blickt hatten. Die Stühle in @abb-opsroom sind sehr Pregnant, diese Beisitzen ein bedienfeld die funktion des stühle werden in @abb-opsroom-stuhl genauer aufgeschlusselt
#abbildung(
  align(center, image("../abbildungen/Opsroom_Stuhl.png", width: 65%)),
  titel: [Stuhl innerhalb des Operationsraums],
  quelle: [Eigene Darstellung in Anlehnung an #zitat(<Arnold20202140>, seite: 31)],
)<abb-opsroom-stuhl>
Die linke Lehne des Stuhls beinhaltete die Bedienung. Die drei quadratischen Knöpfe oben in @abb-opsroom-stuhl steuerten die drei unterschiedlichen Data-Feed-Bildschirme. Die rechteckige Taste diente zur Bestätigung.#vgl(<brain-of-the-firm>, seite: 269) Die 5 darunterliegenden geometrischen Knöpfe wurden genutzt um zwischen den Datensätzen zu navigieren. Aufgebaut waren diese nach einer 5-Bit-Logik – es gab 5 Knopfe die etwender an oder aus sein konnten – so konnten 32 unterschiedliche Kombination gedrückt werden. Das Bedienfeld des Operationsraums war explizit auf Arbeiter\*innen zugeschnitten. Die Steuerung sollte leicht bedienbar sein. Beer nannte es auch #emph()[Big Hand Control] da die Knöpfe zusätzlich sehr robust waren. #vgl(<brain-of-the-firm>, seite: 270) Die restlichen Knöpfe sind nicht klar dokumentiert. Bei der rechten Armlehne war ein Aschenbecher sowie eine Glasablage eingebaut. #vgl(<Arnold20202140>, seite: 31)
== Anwendung und Verlauf

== Ende des Projekts
