#import "../template/fom.typ": *
= Zusammenfassung und Ausblick
Das Beispiel Azure Monitor zeigt, dass das #abk("VSM") auch auf andere Systeme als die chilenische Wirtschaft anwendbar ist. Das #abk("VSM") ist nicht nur auf Azure Monitor – oder ähnliche Monitoring-Tools wie #abk("AWS") CloudWatch#vgl(<WhatAmazonCloudWatch>) oder das Cloud Monitoring bei #abk("GCP")#vgl(<gcpcm>) – anwendbar, sondern auch auf Unternehmen, da Beer das #abk("VSM") ursprünglich für Unternehmen entwickelt hat.#vgl(<espejoCybersynBigData2022>, seite: 1166) Beer schrieb 1985 sogar ein Buch darüber, wie das #abk("VSM") in Unternehmen angewendet werden kann.#vgl(<beerDtsfo>) Espejo hat Mitte der 1980er-Jahre #emph()[Syncho] gegründet,#footnote[Syncho Ltd. ist laut LinkedIn-Unternehmensprofil weiterhin aktiv vertreten, vgl. #zitat(<synchoLinkedIn>)] um die Anwendung des #abk("VSM") als Dienstleistung anzubieten (@abb-zeitstarhl). In den Unternehmen wurde später Cyberfilter genutzt (@abb-zeitstarhl).#vgl(<espejoCybersynBigData2022>, seite: 1166)
\ Azure Monitor hat durch Smart Detection eine vergleichbare Methodik zum Ausnahmeprinzip Cyberstrides. Die Meldungen bei Smart Detection sind nicht algedonisch, sondern beschreiben ein auftretendes Problem genauer.
\ Ein Rückkanal wie Cyberfolk ist bis heute kein Standard in #abk("DSS").#vgl-kap(<gluchowskiManagementSupportSysteme2008a>, kap: [3.2.2 Bestandteile und Aufbau der DSS]) Wie in Kapitel 5.2 dargelegt, kann bei dem Azure-Monitor-Beispiel ein Ticketsystem als Rückkanal genutzt werden.
\ Cybernet ist heute durch das Internet abgelöst; als Cybersyn entwickelt wurde, existierte das Internet noch nicht.#footnote[1971 gab es schon das ARPANET, den Vorläufer des heutigen Internets. Vgl. #zitat-kap(<medinaCyberneticRevolutinaries2014>, kap: "2 Cybernetics in the Battle for Production").] Die Idee von Cybernet war es, eine Möglichkeit zu schaffen, in Echtzeit zu kommunizieren; dies war wegen technischer Limitationen nicht möglich.#vgl-kap(<medinaCyberneticRevolutinaries2014>, kap: "3 Designing a Network") Live-Daten sind heutzutage im #abk("DSS")-Kontext relevant, wie bei Azure Monitor mit Performance-Daten.#vgl(<austinmccollumAzureMonitorUebersicht>)
\ CHECO ist eine Besonderheit Cybersyns; Azure Monitor enthält keine Komponente mit Zukunftssimulation.#vgl(<austinmccollumAzureMonitorUebersicht>) Innerhalb eines #abk("DSS") würde CHECO einer Modellbank entsprechen.#vgl-kap(<gluchowskiManagementSupportSysteme2008a>, kap: [3.2.2 Bestandteile und Aufbau der DSS])
\ Die spätere Anwendung des #abk("VSM") und dessen Übertragbarkeit auf Anwendungen wie Azure Monitor zeigen, dass die Theorie hinter dem Projekt ebenso in modernen Kontexten funktioniert. Cybersyn selbst litt damals an den technischen Limitationen sowie an politischen Komplikationen.#vgl-kap(<medinaCyberneticRevolutinaries2014>, kap: "4 Constructing the Liberty Machine") Dies unterstreicht auch den Punkt von Espejo, dass das #abk("VSM") die größte Errungenschaft des Projekts war.#vgl(<espejoCybersynBigData2022>, seite: 1165)

